// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync_msg.proto

package com.baidu.personal.fist.grpc;

public final class SyncMsg {
  private SyncMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SyncRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.baidu.personal.fist.grpc.SyncRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes file_path = 1;</code>
     */
    com.google.protobuf.ByteString getFilePath();

    /**
     * <code>bytes file_content = 2;</code>
     */
    com.google.protobuf.ByteString getFileContent();
  }
  /**
   * <pre>
   * 定义请求参数
   * </pre>
   *
   * Protobuf type {@code com.baidu.personal.fist.grpc.SyncRequest}
   */
  public  static final class SyncRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.baidu.personal.fist.grpc.SyncRequest)
      SyncRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SyncRequest.newBuilder() to construct.
    private SyncRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SyncRequest() {
      filePath_ = com.google.protobuf.ByteString.EMPTY;
      fileContent_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SyncRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              filePath_ = input.readBytes();
              break;
            }
            case 18: {

              fileContent_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SyncMsg.internal_static_com_baidu_personal_fist_grpc_SyncRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SyncMsg.internal_static_com_baidu_personal_fist_grpc_SyncRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SyncRequest.class, Builder.class);
    }

    public static final int FILE_PATH_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString filePath_;
    /**
     * <code>bytes file_path = 1;</code>
     */
    public com.google.protobuf.ByteString getFilePath() {
      return filePath_;
    }

    public static final int FILE_CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString fileContent_;
    /**
     * <code>bytes file_content = 2;</code>
     */
    public com.google.protobuf.ByteString getFileContent() {
      return fileContent_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!filePath_.isEmpty()) {
        output.writeBytes(1, filePath_);
      }
      if (!fileContent_.isEmpty()) {
        output.writeBytes(2, fileContent_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!filePath_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, filePath_);
      }
      if (!fileContent_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, fileContent_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SyncRequest)) {
        return super.equals(obj);
      }
      SyncRequest other = (SyncRequest) obj;

      boolean result = true;
      result = result && getFilePath()
          .equals(other.getFilePath());
      result = result && getFileContent()
          .equals(other.getFileContent());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILE_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getFilePath().hashCode();
      hash = (37 * hash) + FILE_CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getFileContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SyncRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SyncRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SyncRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SyncRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SyncRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SyncRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SyncRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SyncRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SyncRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SyncRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SyncRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SyncRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SyncRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 定义请求参数
     * </pre>
     *
     * Protobuf type {@code com.baidu.personal.fist.grpc.SyncRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.baidu.personal.fist.grpc.SyncRequest)
        SyncRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SyncMsg.internal_static_com_baidu_personal_fist_grpc_SyncRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SyncMsg.internal_static_com_baidu_personal_fist_grpc_SyncRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SyncRequest.class, Builder.class);
      }

      // Construct using com.baidu.personal.fist.grpc.SyncMsg.SyncRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        filePath_ = com.google.protobuf.ByteString.EMPTY;

        fileContent_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SyncMsg.internal_static_com_baidu_personal_fist_grpc_SyncRequest_descriptor;
      }

      public SyncRequest getDefaultInstanceForType() {
        return SyncRequest.getDefaultInstance();
      }

      public SyncRequest build() {
        SyncRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SyncRequest buildPartial() {
        SyncRequest result = new SyncRequest(this);
        result.filePath_ = filePath_;
        result.fileContent_ = fileContent_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SyncRequest) {
          return mergeFrom((SyncRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SyncRequest other) {
        if (other == SyncRequest.getDefaultInstance()) return this;
        if (other.getFilePath() != com.google.protobuf.ByteString.EMPTY) {
          setFilePath(other.getFilePath());
        }
        if (other.getFileContent() != com.google.protobuf.ByteString.EMPTY) {
          setFileContent(other.getFileContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SyncRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SyncRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString filePath_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes file_path = 1;</code>
       */
      public com.google.protobuf.ByteString getFilePath() {
        return filePath_;
      }
      /**
       * <code>bytes file_path = 1;</code>
       */
      public Builder setFilePath(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        filePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes file_path = 1;</code>
       */
      public Builder clearFilePath() {
        
        filePath_ = getDefaultInstance().getFilePath();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString fileContent_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes file_content = 2;</code>
       */
      public com.google.protobuf.ByteString getFileContent() {
        return fileContent_;
      }
      /**
       * <code>bytes file_content = 2;</code>
       */
      public Builder setFileContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes file_content = 2;</code>
       */
      public Builder clearFileContent() {
        
        fileContent_ = getDefaultInstance().getFileContent();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.baidu.personal.fist.grpc.SyncRequest)
    }

    // @@protoc_insertion_point(class_scope:com.baidu.personal.fist.grpc.SyncRequest)
    private static final SyncRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SyncRequest();
    }

    public static SyncRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SyncRequest>
        PARSER = new com.google.protobuf.AbstractParser<SyncRequest>() {
      public SyncRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SyncRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SyncRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SyncRequest> getParserForType() {
      return PARSER;
    }

    public SyncRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SyncResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.baidu.personal.fist.grpc.SyncResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 成功or失败
     * </pre>
     *
     * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result result = 1;</code>
     */
    boolean hasResult();
    /**
     * <pre>
     * 成功or失败
     * </pre>
     *
     * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result result = 1;</code>
     */
    SyncResponse.Result getResult();
    /**
     * <pre>
     * 成功or失败
     * </pre>
     *
     * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result result = 1;</code>
     */
    SyncResponse.ResultOrBuilder getResultOrBuilder();
  }
  /**
   * <pre>
   * 定义响应参数
   * </pre>
   *
   * Protobuf type {@code com.baidu.personal.fist.grpc.SyncResponse}
   */
  public  static final class SyncResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.baidu.personal.fist.grpc.SyncResponse)
      SyncResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SyncResponse.newBuilder() to construct.
    private SyncResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SyncResponse() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SyncResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              Result.Builder subBuilder = null;
              if (result_ != null) {
                subBuilder = result_.toBuilder();
              }
              result_ = input.readMessage(Result.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(result_);
                result_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SyncMsg.internal_static_com_baidu_personal_fist_grpc_SyncResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SyncMsg.internal_static_com_baidu_personal_fist_grpc_SyncResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SyncResponse.class, Builder.class);
    }

    public interface ResultOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.baidu.personal.fist.grpc.SyncResponse.Result)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result.ResultCode res_code = 1;</code>
       */
      int getResCodeValue();
      /**
       * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result.ResultCode res_code = 1;</code>
       */
      Result.ResultCode getResCode();

      /**
       * <code>bytes err_msg = 2;</code>
       */
      com.google.protobuf.ByteString getErrMsg();
    }
    /**
     * Protobuf type {@code com.baidu.personal.fist.grpc.SyncResponse.Result}
     */
    public  static final class Result extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.baidu.personal.fist.grpc.SyncResponse.Result)
        ResultOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Result.newBuilder() to construct.
      private Result(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Result() {
        resCode_ = 0;
        errMsg_ = com.google.protobuf.ByteString.EMPTY;
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Result(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();

                resCode_ = rawValue;
                break;
              }
              case 18: {

                errMsg_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SyncMsg.internal_static_com_baidu_personal_fist_grpc_SyncResponse_Result_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SyncMsg.internal_static_com_baidu_personal_fist_grpc_SyncResponse_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Result.class, Builder.class);
      }

      /**
       * Protobuf enum {@code com.baidu.personal.fist.grpc.SyncResponse.Result.ResultCode}
       */
      public enum ResultCode
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>SUCCESS = 0;</code>
         */
        SUCCESS(0),
        /**
         * <code>ERROR = 1;</code>
         */
        ERROR(1),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>SUCCESS = 0;</code>
         */
        public static final int SUCCESS_VALUE = 0;
        /**
         * <code>ERROR = 1;</code>
         */
        public static final int ERROR_VALUE = 1;


        public final int getNumber() {
          if (this == UNRECOGNIZED) {
            throw new IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
          }
          return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static ResultCode valueOf(int value) {
          return forNumber(value);
        }

        public static ResultCode forNumber(int value) {
          switch (value) {
            case 0: return SUCCESS;
            case 1: return ERROR;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            ResultCode> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<ResultCode>() {
                public ResultCode findValueByNumber(int number) {
                  return ResultCode.forNumber(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(ordinal());
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return Result.getDescriptor().getEnumTypes().get(0);
        }

        private static final ResultCode[] VALUES = values();

        public static ResultCode valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
          }
          return VALUES[desc.getIndex()];
        }

        private final int value;

        private ResultCode(int value) {
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:com.baidu.personal.fist.grpc.SyncResponse.Result.ResultCode)
      }

      public static final int RES_CODE_FIELD_NUMBER = 1;
      private int resCode_;
      /**
       * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result.ResultCode res_code = 1;</code>
       */
      public int getResCodeValue() {
        return resCode_;
      }
      /**
       * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result.ResultCode res_code = 1;</code>
       */
      public ResultCode getResCode() {
        ResultCode result = ResultCode.valueOf(resCode_);
        return result == null ? ResultCode.UNRECOGNIZED : result;
      }

      public static final int ERR_MSG_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString errMsg_;
      /**
       * <code>bytes err_msg = 2;</code>
       */
      public com.google.protobuf.ByteString getErrMsg() {
        return errMsg_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (resCode_ != ResultCode.SUCCESS.getNumber()) {
          output.writeEnum(1, resCode_);
        }
        if (!errMsg_.isEmpty()) {
          output.writeBytes(2, errMsg_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (resCode_ != ResultCode.SUCCESS.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, resCode_);
        }
        if (!errMsg_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, errMsg_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Result)) {
          return super.equals(obj);
        }
        Result other = (Result) obj;

        boolean result = true;
        result = result && resCode_ == other.resCode_;
        result = result && getErrMsg()
            .equals(other.getErrMsg());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + RES_CODE_FIELD_NUMBER;
        hash = (53 * hash) + resCode_;
        hash = (37 * hash) + ERR_MSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrMsg().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Result parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Result parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Result parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Result parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Result parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Result parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Result parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Result parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Result parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Result parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Result parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Result parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Result prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.baidu.personal.fist.grpc.SyncResponse.Result}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.baidu.personal.fist.grpc.SyncResponse.Result)
          ResultOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return SyncMsg.internal_static_com_baidu_personal_fist_grpc_SyncResponse_Result_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return SyncMsg.internal_static_com_baidu_personal_fist_grpc_SyncResponse_Result_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Result.class, Builder.class);
        }

        // Construct using com.baidu.personal.fist.grpc.SyncMsg.SyncResponse.Result.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          resCode_ = 0;

          errMsg_ = com.google.protobuf.ByteString.EMPTY;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return SyncMsg.internal_static_com_baidu_personal_fist_grpc_SyncResponse_Result_descriptor;
        }

        public Result getDefaultInstanceForType() {
          return Result.getDefaultInstance();
        }

        public Result build() {
          Result result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Result buildPartial() {
          Result result = new Result(this);
          result.resCode_ = resCode_;
          result.errMsg_ = errMsg_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Result) {
            return mergeFrom((Result)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Result other) {
          if (other == Result.getDefaultInstance()) return this;
          if (other.resCode_ != 0) {
            setResCodeValue(other.getResCodeValue());
          }
          if (other.getErrMsg() != com.google.protobuf.ByteString.EMPTY) {
            setErrMsg(other.getErrMsg());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Result parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Result) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int resCode_ = 0;
        /**
         * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result.ResultCode res_code = 1;</code>
         */
        public int getResCodeValue() {
          return resCode_;
        }
        /**
         * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result.ResultCode res_code = 1;</code>
         */
        public Builder setResCodeValue(int value) {
          resCode_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result.ResultCode res_code = 1;</code>
         */
        public ResultCode getResCode() {
          ResultCode result = ResultCode.valueOf(resCode_);
          return result == null ? ResultCode.UNRECOGNIZED : result;
        }
        /**
         * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result.ResultCode res_code = 1;</code>
         */
        public Builder setResCode(ResultCode value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          resCode_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result.ResultCode res_code = 1;</code>
         */
        public Builder clearResCode() {
          
          resCode_ = 0;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString errMsg_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>bytes err_msg = 2;</code>
         */
        public com.google.protobuf.ByteString getErrMsg() {
          return errMsg_;
        }
        /**
         * <code>bytes err_msg = 2;</code>
         */
        public Builder setErrMsg(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          errMsg_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bytes err_msg = 2;</code>
         */
        public Builder clearErrMsg() {
          
          errMsg_ = getDefaultInstance().getErrMsg();
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.baidu.personal.fist.grpc.SyncResponse.Result)
      }

      // @@protoc_insertion_point(class_scope:com.baidu.personal.fist.grpc.SyncResponse.Result)
      private static final Result DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Result();
      }

      public static Result getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Result>
          PARSER = new com.google.protobuf.AbstractParser<Result>() {
        public Result parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Result(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Result> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<Result> getParserForType() {
        return PARSER;
      }

      public Result getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private Result result_;
    /**
     * <pre>
     * 成功or失败
     * </pre>
     *
     * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result result = 1;</code>
     */
    public boolean hasResult() {
      return result_ != null;
    }
    /**
     * <pre>
     * 成功or失败
     * </pre>
     *
     * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result result = 1;</code>
     */
    public Result getResult() {
      return result_ == null ? Result.getDefaultInstance() : result_;
    }
    /**
     * <pre>
     * 成功or失败
     * </pre>
     *
     * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result result = 1;</code>
     */
    public ResultOrBuilder getResultOrBuilder() {
      return getResult();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != null) {
        output.writeMessage(1, getResult());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResult());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SyncResponse)) {
        return super.equals(obj);
      }
      SyncResponse other = (SyncResponse) obj;

      boolean result = true;
      result = result && (hasResult() == other.hasResult());
      if (hasResult()) {
        result = result && getResult()
            .equals(other.getResult());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResult()) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResult().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SyncResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SyncResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SyncResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SyncResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SyncResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SyncResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SyncResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SyncResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SyncResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SyncResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SyncResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SyncResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SyncResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 定义响应参数
     * </pre>
     *
     * Protobuf type {@code com.baidu.personal.fist.grpc.SyncResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.baidu.personal.fist.grpc.SyncResponse)
        SyncResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SyncMsg.internal_static_com_baidu_personal_fist_grpc_SyncResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SyncMsg.internal_static_com_baidu_personal_fist_grpc_SyncResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SyncResponse.class, Builder.class);
      }

      // Construct using com.baidu.personal.fist.grpc.SyncMsg.SyncResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (resultBuilder_ == null) {
          result_ = null;
        } else {
          result_ = null;
          resultBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SyncMsg.internal_static_com_baidu_personal_fist_grpc_SyncResponse_descriptor;
      }

      public SyncResponse getDefaultInstanceForType() {
        return SyncResponse.getDefaultInstance();
      }

      public SyncResponse build() {
        SyncResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SyncResponse buildPartial() {
        SyncResponse result = new SyncResponse(this);
        if (resultBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SyncResponse) {
          return mergeFrom((SyncResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SyncResponse other) {
        if (other == SyncResponse.getDefaultInstance()) return this;
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SyncResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SyncResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Result result_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Result, Result.Builder, ResultOrBuilder> resultBuilder_;
      /**
       * <pre>
       * 成功or失败
       * </pre>
       *
       * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result result = 1;</code>
       */
      public boolean hasResult() {
        return resultBuilder_ != null || result_ != null;
      }
      /**
       * <pre>
       * 成功or失败
       * </pre>
       *
       * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result result = 1;</code>
       */
      public Result getResult() {
        if (resultBuilder_ == null) {
          return result_ == null ? Result.getDefaultInstance() : result_;
        } else {
          return resultBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 成功or失败
       * </pre>
       *
       * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result result = 1;</code>
       */
      public Builder setResult(Result value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          resultBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 成功or失败
       * </pre>
       *
       * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result result = 1;</code>
       */
      public Builder setResult(
          Result.Builder builderForValue) {
        if (resultBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          resultBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 成功or失败
       * </pre>
       *
       * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result result = 1;</code>
       */
      public Builder mergeResult(Result value) {
        if (resultBuilder_ == null) {
          if (result_ != null) {
            result_ =
              Result.newBuilder(result_).mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          resultBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 成功or失败
       * </pre>
       *
       * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result result = 1;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = null;
          onChanged();
        } else {
          result_ = null;
          resultBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 成功or失败
       * </pre>
       *
       * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result result = 1;</code>
       */
      public Result.Builder getResultBuilder() {
        
        onChanged();
        return getResultFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 成功or失败
       * </pre>
       *
       * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result result = 1;</code>
       */
      public ResultOrBuilder getResultOrBuilder() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilder();
        } else {
          return result_ == null ?
              Result.getDefaultInstance() : result_;
        }
      }
      /**
       * <pre>
       * 成功or失败
       * </pre>
       *
       * <code>.com.baidu.personal.fist.grpc.SyncResponse.Result result = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Result, Result.Builder, ResultOrBuilder>
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Result, Result.Builder, ResultOrBuilder>(
                  getResult(),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.baidu.personal.fist.grpc.SyncResponse)
    }

    // @@protoc_insertion_point(class_scope:com.baidu.personal.fist.grpc.SyncResponse)
    private static final SyncResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SyncResponse();
    }

    public static SyncResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SyncResponse>
        PARSER = new com.google.protobuf.AbstractParser<SyncResponse>() {
      public SyncResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SyncResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SyncResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SyncResponse> getParserForType() {
      return PARSER;
    }

    public SyncResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_personal_fist_grpc_SyncRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_baidu_personal_fist_grpc_SyncRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_personal_fist_grpc_SyncResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_baidu_personal_fist_grpc_SyncResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_personal_fist_grpc_SyncResponse_Result_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_baidu_personal_fist_grpc_SyncResponse_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016sync_msg.proto\022\034com.baidu.personal.fis" +
      "t.grpc\"6\n\013SyncRequest\022\021\n\tfile_path\030\001 \001(\014" +
      "\022\024\n\014file_content\030\002 \001(\014\"\343\001\n\014SyncResponse\022" +
      "A\n\006result\030\001 \001(\01321.com.baidu.personal.fis" +
      "t.grpc.SyncResponse.Result\032\217\001\n\006Result\022N\n" +
      "\010res_code\030\001 \001(\0162<.com.baidu.personal.fis" +
      "t.grpc.SyncResponse.Result.ResultCode\022\017\n" +
      "\007err_msg\030\002 \001(\014\"$\n\nResultCode\022\013\n\007SUCCESS\020" +
      "\000\022\t\n\005ERROR\020\0012\275\004\n\013SyncService\022l\n\021processF" +
      "ileCreate\022).com.baidu.personal.fist.grpc" +
      ".SyncRequest\032*.com.baidu.personal.fist.g" +
      "rpc.SyncResponse\"\000\022l\n\021processFileModify\022" +
      ").com.baidu.personal.fist.grpc.SyncReque" +
      "st\032*.com.baidu.personal.fist.grpc.SyncRe" +
      "sponse\"\000\022l\n\021processFileDelete\022).com.baid" +
      "u.personal.fist.grpc.SyncRequest\032*.com.b" +
      "aidu.personal.fist.grpc.SyncResponse\"\000\022q" +
      "\n\026processDirectoryCreate\022).com.baidu.per" +
      "sonal.fist.grpc.SyncRequest\032*.com.baidu." +
      "personal.fist.grpc.SyncResponse\"\000\022q\n\026pro" +
      "cessDirectoryDelete\022).com.baidu.personal" +
      ".fist.grpc.SyncRequest\032*.com.baidu.perso" +
      "nal.fist.grpc.SyncResponse\"\000B\013B\007SyncMsgP" +
      "\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_baidu_personal_fist_grpc_SyncRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_baidu_personal_fist_grpc_SyncRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_baidu_personal_fist_grpc_SyncRequest_descriptor,
        new String[] { "FilePath", "FileContent", });
    internal_static_com_baidu_personal_fist_grpc_SyncResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_baidu_personal_fist_grpc_SyncResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_baidu_personal_fist_grpc_SyncResponse_descriptor,
        new String[] { "Result", });
    internal_static_com_baidu_personal_fist_grpc_SyncResponse_Result_descriptor =
      internal_static_com_baidu_personal_fist_grpc_SyncResponse_descriptor.getNestedTypes().get(0);
    internal_static_com_baidu_personal_fist_grpc_SyncResponse_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_baidu_personal_fist_grpc_SyncResponse_Result_descriptor,
        new String[] { "ResCode", "ErrMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
